[package]
name = "oracle-studio-ui"
version = "0.1.0"
description = "Leptos CSR interface for Oracle Studio"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["csr"]
csr = ["leptos/csr"]

[dependencies]
base64.workspace = true
gloo-net.workspace = true
leptos.workspace = true
leptos_router.workspace = true
oracle-studio-chart-view = { version = "0.1.0", path = "../oracle-studio-chart-view" }
oracle-studio-protocol = { version = "0.1.0", path = "../oracle-studio-protocol" }
serde = { workspace = true }
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Crypto",
    "History",
    "HtmlInputElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "Location",
    "Window",
] }
